kind: Service
apiVersion: v1
metadata:
  name: svc-demo
  labels:
    app: demo
spec:
  selector:
    app: demo
  ports:
    - protocol: TCP
      port: 8002
      targetPort:
        8002
        # nodePort: 30085
  clusterIP: None
  # type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: svc-demo
  labels:
    app: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
        - name: demo
          image: mx2542/anti-demo:1.0
          command:
            - "uvicorn"
          args:
            - "src.main:app"
            - "--reload"
            - "--host=0.0.0.0"
            - "--port=8002"
          ports:
            - containerPort: 8002
          imagePullPolicy: Always
